# Generated by Django 3.2 on 2021-05-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='labToCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labNumber', models.IntegerField()),
                ('courseNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='myAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('userType', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='myContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=40)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('emailAddress', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='myCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=20)),
                ('courseNumber', models.IntegerField()),
                ('instructorUserName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='myCourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumber', models.IntegerField()),
                ('instructorUserName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='myLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labName', models.CharField(max_length=20)),
                ('labNumber', models.IntegerField()),
                ('taUserName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='myLabTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labNumber', models.IntegerField()),
                ('taUserName', models.CharField(max_length=40)),
            ],
        ),
    ]
