# Generated by Django 3.2 on 2021-04-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycontact',
            name='emailAddress',
            field=models.CharField(max_length=40),
        ),
    ]
