# Generated by Django 3.2 on 2021-04-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_Scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=15)),
                ('courseNumber', models.IntegerField()),
                ('courseInstructorFirstName', models.CharField(max_length=30)),
                ('courseInstructorLastName', models.CharField(max_length=30)),
                ('courseDescription', models.CharField(max_length=1000)),
                ('courseStartDate', models.CharField(max_length=12)),
                ('courseEndDate', models.CharField(max_length=12)),
            ],
        ),
    ]
